services:
  - type: web
    name: backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_VERSION
        value: 18

  - type: web
    name: frontend
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    env:
      - key: NODE_VERSION
        value: 18
    headers:
      - source: /*
        headers:
          - key: Cache-Control
            value: no-store