services:
  - type: web
    name: web
    buildCommand: npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /**
        destination: /index.html
    headers:
      - source: /**
        headers:
          - key: Cache-Control
            value: no-store