services:
  - type: web
    name: web
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    env:
      - key: NODE_VERSION
        value: 18
    headers:
      - source: /*
        headers:
          - key: Cache-Control
            value: no-store